# Workflow
# Should Have a Name [No indentations required for naming the workflow]
name: Hello

# on tells when the workflow should run (Add indentation by Tab)
on: 
  # workflow_dispatch: 
  push:

# Job tells what the workflow should do, there can be one or more than one jobs, hence we write jobs
# jobs is an object so need indentation
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!" 

  # # 1st job (give indentation)
  # say-hello:
  #   # creates an Ephemeral Container with Ubuntu running
  #   runs-on: ubuntu-latest
  #   # that Ephemeral container will have steps to execute, hence name those steps and use run: run has the command
  #   steps:
  #     - name: Say hello to World
  #       run: echo "Hello World"
  
