# Workflow
# Should Have a Name [No indentations required for naming the workflow]
name: Hello

# on tells when the workflow should run (Add indentation by Tab)
on: 
  # workflow_dispatch: 
  push:

# Job tells what the workflow should do, there can be one or more than one jobs, hence we write jobs
# jobs is an object so need indentation
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!" 

      # Print the current date and time
      - name: Print current date and time
        run: date

      # print branch name
      - name: Print branch name
        run: echo "The branch is ${{ github.ref_name }}"

      # list repo files
      - name: List files in repository
        run: ls -la

      # print operating system information
      - name: Print operating system information
        run: echo "The Operating System is ${{ runner.os }}"

       # adding step to fail
      - name: Force a build failure
        run: |
          echo "Simulating an error..."
          exit 0


  # # 1st job (give indentation)
  # say-hello:
  #   # creates an Ephemeral Container with Ubuntu running
  #   runs-on: ubuntu-latest
  #   # that Ephemeral container will have steps to execute, hence name those steps and use run: run has the command
  #   steps:
  #     - name: Say hello to World
  #       run: echo "Hello World"
  
